// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, token, user_id, expires_at, revoked_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, token, user_id, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteRefreshTokenByToken = `-- name: DeleteRefreshTokenByToken :exec
DELETE FROM refresh_tokens 
WHERE token = $1
`

func (q *Queries) DeleteRefreshTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenByToken, token)
	return err
}

const deleteRefreshTokenByUserID = `-- name: DeleteRefreshTokenByUserID :exec
DELETE FROM refresh_tokens 
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokenByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenByUserID, userID)
	return err
}

const extendTokenRevoke = `-- name: ExtendTokenRevoke :exec
UPDATE refresh_tokens 
SET expires_at = $1 
WHERE token = $2
`

type ExtendTokenRevokeParams struct {
	ExpiresAt time.Time
	Token     string
}

func (q *Queries) ExtendTokenRevoke(ctx context.Context, arg ExtendTokenRevokeParams) error {
	_, err := q.db.ExecContext(ctx, extendTokenRevoke, arg.ExpiresAt, arg.Token)
	return err
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT id, created_at, updated_at, token, user_id, expires_at, revoked_at FROM refresh_tokens 
WHERE token = $1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenByUserID = `-- name: GetRefreshTokenByUserID :one
SELECT id, created_at, updated_at, token, user_id, expires_at, revoked_at FROM refresh_tokens 
WHERE user_id = $1
`

func (q *Queries) GetRefreshTokenByUserID(ctx context.Context, userID uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByUserID, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserIDByRefreshToken = `-- name: GetUserIDByRefreshToken :one
SELECT id, created_at, updated_at, token, user_id, expires_at, revoked_at FROM refresh_tokens 
WHERE token = $1
`

func (q *Queries) GetUserIDByRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshTokenByToken = `-- name: RevokeRefreshTokenByToken :exec
UPDATE refresh_tokens 
SET revoked_at = NOW() 
WHERE token = $1
`

func (q *Queries) RevokeRefreshTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByToken, token)
	return err
}

const revokeRefreshTokenByUserID = `-- name: RevokeRefreshTokenByUserID :exec
UPDATE refresh_tokens 
SET revoked_at = NOW() 
WHERE user_id = $1
`

func (q *Queries) RevokeRefreshTokenByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByUserID, userID)
	return err
}
